meta_product_name: "Fast Track"
meta_title: "Fast Track - The best solution for new and experienced traders to track their portfolio with up to date data's in real time."
meta_description: "Fast Track is the app that allows people to track their portfolio avec stock wherever they want. A friendly-user web application that will change your view about finance trading"
meta_image: "app/assets/images/fasstrack.jpeg" # should exist in `app/assets/images/`
